In [1]:
import sys
sys.path.append('..')
import os
# PROJECT_ROOT = os.path.dirname()

from pathlib import Path
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf 



In [26]:
def load_results():
    path = Path('../artifacts/')

    experiments = []
    for i in path.glob('*'):
        try:
            new_path = str(i) + '/metrics.json'
            f = open(new_path)
            data = json.load(f)
            experiments.append(data)
        except  Exception as e:
            print(e)
        finally:
            f.close()

    df = pd.DataFrame(experiments)
    df = df.sort_values(by='acc_test', ascending=False)
    return df


def load_crossvalidation_results():
    path = Path('../artifacts/')

    experiments = []
    for i in path.glob('*_CV_*'):
        for j in i.glob('*'):
            try:
  
                new_path = str(j) + str(Path('/metrics.json'))
                f = open(new_path)
                data = json.load(f)
                experiments.append(data)
            except  Exception as e:
                print(e)
            finally:
                f.close()

    if experiments:
        df = pd.DataFrame(experiments)
        df = df.sort_values(by='acc_test', ascending=False)
        return df
    else:
        return pd.DataFrame({})




In [16]:
df = load_results()
df.head(50)

[Errno 2] No such file or directory: '..\\artifacts\\20221114_15-22-35_CV_AlexNet_dataset_image_100x100/metrics.json'
[Errno 2] No such file or directory: '..\\artifacts\\20221114_15-25-45_CV_AlexNet_dataset_image_100x100/metrics.json'


dataset     model            date_time  epochs  batch_size  \
1  dataset_image_100x100     LeNet  14/11/2022 15:14:25       5          25   
0  dataset_image_100x100   AlexNet  14/11/2022 15:14:14       5          25   
2  dataset_image_100x100  ResNet50  14/11/2022 15:15:01       5          25   
3  dataset_image_100x100     VGG16  14/11/2022 15:15:23       5          25   
4  dataset_image_100x100  Xception  14/11/2022 15:15:58       5          25   

  training_mode  acc_test   acc_val  acc_train  precision    recall    fscore  \
1       default  0.828221  0.892308   0.924528   0.839892  0.828221  0.818644   
0       default  0.711656  0.861538   0.740995   0.711222  0.711656  0.683503   
2       default  0.631902  0.553846   0.931389   0.399300  0.631902  0.489368   
3       default  0.631902  0.553846   0.638079   0.399300  0.631902  0.489368   
4       default  0.631902  0.553846   0.951973   0.399300  0.631902  0.489368   

      kappa       auc  auc_precision_recall optmizer_setup  \
1  0.603130  0.911165              0.870516           adam   
0  0.310627  0.740615              0.691257           adam   
2  0.000000  0.687379              0.629371           adam   
3  0.000000  0.394256              0.296709           adam   
4  0.000000  0.786893              0.648261           adam   

                                    experiment_code  \
1     20221114_15-14-20_LeNet_dataset_image_100x100   
0   20221114_15-14-06_AlexNet_dataset_image_100x100   
2  20221114_15-14-32_ResNet50_dataset_image_100x100   
3     20221114_15-15-08_VGG16_dataset_image_100x100   
4  20221114_15-15-29_Xception_dataset_image_100x100   

                             experiment_git_hash experiment_git_branch  
1  b'6af6808b4c0e4b186a4e2d13928d90875e2f1dda\n'                  main  
0  b'6af6808b4c0e4b186a4e2d13928d90875e2f1dda\n'                  main  
2  b'6af6808b4c0e4b186a4e2d13928d90875e2f1dda\n'                  main  
3  b'6af6808b4c0e4b186a4e2d13928d90875e2f1dda\n'                  main  
4  b'6af6808b4c0e4b186a4e2d13928d90875e2f1dda\n'                  main

In [17]:
df[df.model=='Transformer']

Empty DataFrame
Columns: [dataset, model, date_time, epochs, batch_size, training_mode, acc_test, acc_val, acc_train, precision, recall, fscore, kappa, auc, auc_precision_recall, optmizer_setup, experiment_code, experiment_git_hash, experiment_git_branch]
Index: []

In [39]:
df_cv = load_crossvalidation_results()
df_cv.groupby(['experiment_code','model','optmizer_setup','folds','data_augumentation']).agg({
    'acc_test':['mean','std'],
    'acc_train':['mean','std'],
    'precision':['mean','std'],
    'recall':['mean','std'],
    'fscore':['mean','std'],
    'auc_precision_recall':['mean','std'],
    'auc':['mean','std'],
    'kappa':['mean','std'],
    })


acc_test  \
                                                                                                         mean   
experiment_code                                    model    optmizer_setup folds data_augumentation             
20221114_16-11-34_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.492146   
20221114_16-12-39_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.492146   
20221114_16-13-04_CV_LeNet_dataset_image_100x100   LeNet    adam           2.0   True                0.466055   
20221114_16-13-25_CV_ResNet50_dataset_image_100... ResNet50 adam           2.0   True                0.492146   
20221114_16-14-29_CV_VGG16_dataset_image_100x100   VGG16    adam           2.0   True                0.630077   
20221114_16-14-58_CV_Xception_dataset_image_100... Xception adam           2.0   True                0.637931   

                                                                                                               \
                                                                                                          std   
experiment_code                                    model    optmizer_setup folds data_augumentation             
20221114_16-11-34_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.183956   
20221114_16-12-39_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.183956   
20221114_16-13-04_CV_LeNet_dataset_image_100x100   LeNet    adam           2.0   True                0.041038   
20221114_16-13-25_CV_ResNet50_dataset_image_100... ResNet50 adam           2.0   True                0.183956   
20221114_16-14-29_CV_VGG16_dataset_image_100x100   VGG16    adam           2.0   True                0.011108   
20221114_16-14-58_CV_Xception_dataset_image_100... Xception adam           2.0   True                     NaN   

                                                                                                    acc_train  \
                                                                                                         mean   
experiment_code                                    model    optmizer_setup folds data_augumentation             
20221114_16-11-34_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.648645   
20221114_16-12-39_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.648645   
20221114_16-13-04_CV_LeNet_dataset_image_100x100   LeNet    adam           2.0   True                0.648645   
20221114_16-13-25_CV_ResNet50_dataset_image_100... ResNet50 adam           2.0   True                0.648645   
20221114_16-14-29_CV_VGG16_dataset_image_100x100   VGG16    adam           2.0   True                0.648645   
20221114_16-14-58_CV_Xception_dataset_image_100... Xception adam           2.0   True                0.617500   

                                                                                                               \
                                                                                                          std   
experiment_code                                    model    optmizer_setup folds data_augumentation             
20221114_16-11-34_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.044046   
20221114_16-12-39_CV_AlexNet_dataset_image_100x100 AlexNet  adam           2.0   True                0.044046   
20221114_16-13-04_CV_LeNet_dataset_image_100x100   LeNet    adam           2.0   True                0.044046   
20221114_16-13-25_CV_ResNet50_dataset_image_100... ResNet50 adam           2.0   True                0.044046   
20221114_16-14-29_CV_VGG16_dataset_image_100x100   VGG16    adam           2.0   True                0.044046   
20221114_16-14-58_CV_Xception_dataset_image_100... Xception adam           2.0   True                     NaN   

                             

In [23]:
from stats.tests import mcnemar_test

model_a = np.load(r'\\wsl.localhost\Ubuntu\home\maodsunix\Development\EEG-research\artifacts\16102022_16-44-43_EEGNeX_8_32_bciiv2a_mat\pred_bool.npy')
model_b = np.load(r'\\wsl.localhost\Ubuntu\home\maodsunix\Development\EEG-research\artifacts\16102022_16-44-43_EEGNeX_8_32_bciiv2a_mat\pred_bool.npy')

mcnemar_test(model_a, model_b)

Contingency table: [[192, 0], [0, 351]]
Some value < 25. Calculating exact p-value
statistic=0.000, p-value=1.00000
Same proportions of errors (fail to reject H0)


(0.0, 1.0, 'fail')

In [79]:

# top_1 = df.iloc[:,1]
# top_3 = df.iloc[:,4]
# top_5 = df.iloc[:,0]
# xlabels = df.iloc[:,-1]

# N = len(df.iloc[:,0])
# ind = np.arange(N)  # the x locations for the groups
# width = 0.2       # the width of the bars

# fig, ax = plt.subplots(figsize=(12,8))
# rects1 = ax.bar(ind, top_1, width, color='#4198d7')
# rects2 = ax.bar(ind + width, top_3, width, color='#f5c767')
# rects3 = ax.bar(ind + 2*width, top_5, width, color='#7a61ba')
# ax.set_xticks(ind + width)
# ax.set_xticklabels(xlabels,fontsize=10)
# ax.set_xlabel("models", fontsize=12)

# ax.set_ylabel("ACC/%", fontsize=12)
# ax.set_title('Metrics for Transformer based models')
# ax.legend((rects1[0], rects2[0],rects3[0]),('Acc Test', 'F1 Score Test','Acc Cross Validation'),bbox_to_anchor=(1.13, 1.01))
# def labelvalue(rects):
#     for rect in rects:
#         height = rect.get_height()
#         ax.text(rect.get_x() + rect.get_width()/2., 1.01*height,
#         str(round(height*100,1))+'%' ,ha='center', va='bottom',fontsize=7)

# labelvalue(rects1)
# labelvalue(rects2)
# labelvalue(rects3)
# plt.savefig('../artifacts/barplot_ml.png',dpi=200, format='png', bbox_inches='tight')
# plt.show()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 16.5 MB/s eta 0:00:0000:010:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.8/233.8 kB 12.5 MB/s eta 0:00:00


In [8]:
import sys
sys.path.append('..')
from data.data_load import load_data_intra
import numpy as np


class A:
    def __init__(self) -> None:
        self.pick_eletrodes = False
        self.one_hot = True
        self.net_dim = 3

for data in load_data_intra('bciiv2a_mat', A(),False):
    x_train, x_test, y_train, y_test, sub = data
    print(x_train.shape)
    print(x_test.shape)
    print(y_train.shape)
    print(np.unique(y_test, ))
    print(y_test)
    print(sub)

(216, 22, 1750)
(54, 22, 1750)
(216,)
[1. 2. 3. 4.]
[1. 2. 1. 4. 1. 2. 1. 4. 4. 4. 3. 4. 1. 2. 4. 4. 2. 4. 1. 3. 2. 3. 1. 2.
 1. 4. 2. 2. 3. 2. 1. 4. 3. 2. 2. 1. 4. 1. 3. 2. 4. 3. 3. 4. 1. 1. 2. 3.
 3. 3. 3. 3. 2. 4.]
1
(216, 22, 1750)
(54, 22, 1750)
(216,)
[1. 2. 3. 4.]
[1. 2. 1. 4. 1. 1. 1. 4. 4. 4. 3. 3. 1. 2. 4. 4. 2. 4. 1. 3. 2. 3. 1. 2.
 1. 4. 2. 2. 2. 2. 1. 4. 3. 2. 2. 1. 4. 1. 3. 2. 4. 3. 3. 4. 1. 1. 2. 3.
 3. 3. 3. 3. 2. 4.]
2
(218, 22, 1750)
(55, 22, 1750)
(218,)
[1. 2. 3. 4.]
[2. 1. 4. 2. 2. 4. 4. 3. 2. 3. 3. 2. 4. 3. 4. 1. 1. 2. 3. 4. 2. 3. 2. 4.
 4. 1. 3. 1. 3. 1. 1. 1. 3. 4. 1. 3. 3. 3. 3. 1. 4. 2. 2. 4. 2. 1. 4. 2.
 2. 1. 4. 1. 1. 3. 2.]
3
(216, 22, 1750)
(55, 22, 1750)
(216,)
[1. 2. 3. 4.]
[2. 3. 1. 4. 1. 4. 1. 1. 1. 2. 4. 2. 4. 4. 1. 3. 4. 2. 4. 3. 1. 3. 4. 4.
 1. 2. 1. 3. 2. 2. 3. 2. 1. 4. 2. 2. 1. 4. 1. 3. 2. 4. 3. 3. 4. 1. 1. 2.
 3. 3. 3. 3. 3. 2. 4.]
4
(211, 22, 1750)
(53, 22, 1750)
(211,)
[1. 2. 3. 4.]
[2. 4. 1. 3. 1. 3. 3. 1. 2. 1. 2. 2. 1. 3. 1. 4. 2. 4. 4. 4. 3

In [7]:
np.unique(y_test, return_counts=True)

(array([0., 1.], dtype=float32), array([176,  44]))